### ISSUE TITLE
Ideas for adding checks

### ISSUE THREAD

**Issue by henryiii** [lovaslin/pyBumpHunter#11]
`setup.cfg`:

```python
[flake8]
max-complexity = 12
ignore = E203, E231, E501, E722, W503, B950
select = C,E,F,W,B,B9
```

`.pre-commit-config.yaml`:

```yaml
repos:
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/mgedmin/check-manifest
  rev: "0.43"
  hooks:
  - id: check-manifest
    stages: [manual]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-docstrings
    - flake8-import-order
    - flake8-print
```

`pre-commit run -a` to run locally (`pip install pre-commit`).
